name: OrangeHRM Database Image Scheduled Build Workflow

on:
    schedule:
      - cron:  '*/5 * * * *'
env:
    REPO: ${{ github.repository }}
    BRANCH: ${GITHUB_REF##*/}
jobs:
    ScheduledBuild:
        runs-on: ubuntu-latest
        steps:
            - name: check vars
              run: |
                echo ${{ env.REPO }}
                echo ${{ env.BRANCH }}