name: OrangeHRM Database Image Scheduled Build Workflow

on:
    push:
    schedule:
        - cron: '* * * * *'

if: ${{ github.repository }} == "ChanakaR/github-actions-101"

env:
    REPO: ${{ github.repository }}
    BRANCH: ${GITHUB_REF##*/}
    
jobs:
    ScheduledBuild:
        uses: ChanakaR/github-actions-101/.github/workflows/github-actions-demo.yml@main